# .github/workflows/local-terraform-destroy.yml
name: Local Terraform Destroy (Simulated)

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT_DEV: dev
  ENVIRONMENT_STAGING: staging
  ENVIRONMENT_PROD: prod

jobs:
  destroy:
    name: Destroy Terraform infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Workspace Init
        run: |
          terraform init
          terraform workspace select ${{env.ENVIRONMENT_DEV}} || terraform workspace new ${{env.ENVIRONMENT_DEV}}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="environments/${{env.ENVIRONMENT_DEV}}/${{env.ENVIRONMENT_DEV}}.terraform.tfvars"
