# .github/workflows/test-terraform-apply.yml
name: Test Terraform Apply (Local)

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT_DEV: dev
  ENVIRONMENT_STAGING: staging
  ENVIRONMENT_PROD: prod

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Create fake tfplan artifact
        run: mkdir -p terraform && touch terraform/plan.tfplan

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Select or Create Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{env.ENVIRONMENT_DEV}} || terraform workspace new ${{env.ENVIRONMENT_DEV}}

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -var-file="environments/${{env.ENVIRONMENT_DEV}}/dev.terraform.tfvars"
